#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_split_3x5_2(
		      KC_Q, KC_W, KC_E, KC_R,  KC_T, 		  KC_Y,  KC_U,    KC_I,   KC_O,    KC_SCLN, 
		LCTL(KC_A), KC_S, KC_D, KC_F,  KC_G, 		  KC_H,  KC_J,    KC_K,   KC_L, RCTL(KC_P), 
		LSFT(KC_Z), KC_X, KC_C, KC_V,  KC_B,		  KC_N,  KC_M, KC_COMM, KC_DOT,  KC_SFTENT, 
					   LGUI(KC_BSPC), TO(3), 		OSL(2), HYPR(KC_SPC)
	),

	[1] = LAYOUT_split_3x5_2(
		      KC_Q, KC_W, KC_F, KC_P,  KC_B, 		KC_J,    KC_L,    KC_U,   KC_Y,    KC_SCLN, 
		LCTL(KC_A), KC_R, KC_S, KC_T,  KC_G, 		KC_M,    KC_N,    KC_E,   KC_I, RCTL(KC_O), 
		LSFT(KC_Z), KC_X, KC_C, KC_D,  KC_V, 		KC_K,    KC_H, KC_COMM, KC_DOT,  KC_SFTENT, 
				       LGUI(KC_BSPC), TO(3), 	  OSL(2), KC_SPC
	),

	[2] = LAYOUT_split_3x5_2(
		 KC_TAB,   KC_GRV, XXXXXXX, XXXXXXX,   XXXXXXX, 	XXXXXXX, KC_EXLM,   KC_AT, KC_HASH,  KC_DLR, 
		 KC_ESC,   KC_VOLD, KC_VOLU, KC_MUTE,   KC_NUHS, 	XXXXXXX, KC_PERC, KC_CIRC, KC_AMPR, KC_QUOT, 
		KC_LSFT,   KC_NUBS, XXXXXXX, XXXXXXX,   XXXXXXX, 	XXXXXXX, KC_ASTR, KC_UNDS, KC_PLUS, KC_SLSH, 
							         TO(5),   KC_LALT,	  TO(4),  TO(0)
	),

	[3] = LAYOUT_split_3x5_2(  
		XXXXXXX, KC_BTN1, KC_MS_U, KC_BTN2, KC_ACL0, 	KC_PGUP,  KC_HOME,     KC_UP,   KC_END, XXXXXXX, 
		KC_LCTL, KC_MS_L, KC_MS_D, KC_MS_R, KC_ACL1, 	KC_PGDN,  KC_LEFT,   KC_DOWN,  KC_RGHT,  KC_DEL, 
		KC_LSFT, KC_WH_U, KC_BTN3, KC_WH_D, KC_ACL2,    XXXXXXX,  XXXXXXX,   XXXXXXX,  XXXXXXX, XXXXXXX, 
								   KC_BSPC,  KC_DEL,	XXXXXXX,     TO(0)
	),

	[4] = LAYOUT_split_3x5_2(
		LALT(KC_F4), KC_F1,  KC_F2,  KC_F3,   KC_F4, 		XXXXXXX, KC_1, KC_2,    KC_3,   KC_4, 
		    KC_LCTL, KC_F5,  KC_F6,  KC_F7,   KC_F8, 	    XXXXXXX, KC_5, KC_6,    KC_7,   KC_8, 
		    KC_LSFT, KC_F9, KC_F10, KC_F11,  KC_F12, 	LCA(KC_DEL), KC_9, KC_0, KC_MINS, KC_EQL, 
							       KC_BSPC, KC_LALT,		KC_RALT, TO(0)
	),

	[5] = LAYOUT_split_3x5_2(
		  RESET, XXXXXXX, XXXXXXX,  KC_LPRN, XXXXXXX, 		XXXXXXX, KC_RPRN, XXXXXXX, XXXXXXX, XXXXXXX, 
		XXXXXXX, XXXXXXX, XXXXXXX,  KC_LCBR, XXXXXXX, 	    XXXXXXX, KC_RCBR, XXXXXXX, XXXXXXX, XXXXXXX, 
		XXXXXXX, XXXXXXX, XXXXXXX,  KC_LBRC, XXXXXXX, 		XXXXXXX, KC_RBRC, XXXXXXX, XXXXXXX, XXXXXXX, 
							       KC_BSPC,  XXXXXXX,		XXXXXXX, TO(0)
	)
};
